version: '3.8'
services:
  mysqlDB:
    image: mysql:latest
    container_name: pizzazoDBContainer
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "pizzazo"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    ports:
      - "3307:3306"
    networks:
      - mysqlNetwork

  pizzazoApp:
    image: pizzazoimage
    container_name: pizzazoContainer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      MYSQL_HOST: pizzazoDBContainer
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: pizzazo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      mysqlDB:
        condition: service_healthy
    networks:
      - mysqlNetwork

networks:
  mysqlNetwork:
    driver: bridge
